name: "Check old"
description: >
  Check the released version of a reverse dependency, and keep the result for
  the comparison.

inputs:
  package:
    description: "The reverse dependency to check."
    required: true

runs:
  using: "composite"
  steps:
    - name: "Check old"
      id: main
      env:
        PACKAGE: ${{ inputs.package }}
        _R_CHECK_CRAN_INCOMING_: false
        _R_CHECK_SYSTEM_CLOCK_: false
        _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false
      run: |
        package <- Sys.getenv("PACKAGE")
        options(HTTPUserAgent = "gha")
        path <- download.packages(package, destdir = ".github")[, 2]
        print(path)

        dir <- file.path("revdep", package)
        dir.create(dir, showWarnings = FALSE, recursive = TRUE)
        check <- rcmdcheck::rcmdcheck(path, args = c("--no-manual", "--as-cran"), error_on = "never", check_dir = file.path(dir, "check"))
        file.rename(file.path(dir, "check"), file.path(dir, "old"))
        saveRDS(check, file.path(dir, "old.rds"))
      shell: Rscript {0}
