name: "Actions to set up a Git identity"
description: >
  Configure the Git identity that the generated commits are made under.

runs:
  using: "composite"
  steps:
    - name: Configure Git identity
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash
