name: "Actions to compute a matrix with all suggested packages"
description: >
  Compute a matrix of this package's suggested dependencies, for checking with each one absent.
outputs:
  matrix:
    description: "Generated matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Collect the suggested dependencies
      id: set-matrix
      run: |
        Rscript ./.github/workflows/dep-suggests-matrix/action.R
      shell: bash
